FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY the_wallf.py .

EXPOSE 8080

CMD ["uvicorn", "the_wallf:app", "--host", "0.0.0.0", "--port", "8080"]
